services:
    sonarqube_app:
        image: 
            sonarqube:10.0.0-community
        container_name: 
            sonarqube_app
        command: 
            -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m
        restart: 
            unless-stopped
        mem_limit: 
            "2g"
        cpus: 
            "1"
        depends_on:
            - sonarqube_db
        ports:
            - "9000:9000"
        networks:
            - docker-stack
        environment:
            - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
            - SONARQUBE_JDBC_USERNAME=${POSTGRES_PASSWORD}
            - SONARQUBE_JDBC_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./volumes/sonar-data/data:/opt/sonarqube/data
            - ./volumes/sonar-data/extensions:/opt/sonarqube/extensions
            - ./volumes/sonar-data/logs:/opt/sonarqube/logs

    sonarqube_db:
        image: 
            postgres
        container_name: 
            sonarqube_db
        restart: 
            unless-stopped
        mem_limit: 
            "1g"
        cpus: 
            "1"
        networks:
            - docker-stack
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./volumes/postgres/postgresql:/var/lib/postgresql
            - ./volumes/postgres/data:/var/lib/postgresql/data

networks:
    docker-stack:
        external: true
