version: "3"

services:
  sonarqube:
    image: sonarqube:10.0.0-community
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m
    restart: unless-stopped
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    networks:
      - claro-sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - ./volumes/sonar-data/data:/opt/sonarqube/data
      - ./volumes/sonar-data/extensions:/opt/sonarqube/extensions
      - ./volumes/sonar-data/logs:/opt/sonarqube/logs

  sonarqube_db:
    image: postgres
    container_name: sonarqube_db
    restart: unless-stopped
    networks:
      - claro-sonarqube
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./volumes/postgres/postgresql:/var/lib/postgresql
      - ./volumes/postgres/data:/var/lib/postgresql/data

networks:
  claro-sonarqube:
    external: true