services:
    postgresql:
        image: 
            postgres
        container_name: 
            postgresql
        restart: 
            unless-stopped
        ports:
            - "5432:5432"
        mem_limit: 
            "1g"
        cpus: 
            "1"
        networks:
            - docker-stack
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./volumes/postgresql:/var/lib/postgresql
            - ./volumes/data:/var/lib/postgresql/data
        command:
            - "postgres"
            - "-c"
            - "listen_addresses=*"
            - "-c"
            - "max_connections=100"
            - "-c"
            - "shared_buffers=256MB"

networks:
    docker-stack:
        external: true
