services:
  postgresql:
    image: 
      postgres
    container_name: 
      postgresql
    restart: 
      unless-stopped
    mem_limit: 
      "1g"
    cpus: 
      "1"
    networks:
      - docker-stack
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
      - ./volumes/data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]

networks:
  docker-stack:
    external: true