services:
    n8n_postgresql:
        image: 
            postgres:15
        container_name: 
            n8n_postgresql
        restart: 
            unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./volumes/postgresql:/var/lib/postgresql/data
        networks:
            - docker-stack
        command:
            - "postgres"
            - "-c"
            - "listen_addresses=*"
            - "-c"
            - "max_connections=100"
            - "-c"
            - "shared_buffers=256MB"
        mem_limit: 
            "512m"
        cpus: 
            "0.5"

    n8n_app:
        image: 
            n8nio/n8n
        container_name: 
            n8n_app
        restart: 
            unless-stopped
        ports:
            - "5678:5678"
        environment:
            - DB_TYPE=${DB_TYPE}
            - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
            - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
            - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
            - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
            - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
            - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
            - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
            - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
            - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
            - TZ=${TZ}
        volumes:
            - ./volumes/n8n:/home/node/.n8n
        depends_on:
            - n8n_postgresql
        networks:
            - docker-stack
        mem_limit: 
            "1.5G"
        cpus: 
            "0.5"

networks:
    docker-stack:
        external: true
