services:
  rabbitmq:
    image: 
      rabbitmq:3.12-management  # incluye la interfaz web
    container_name: 
      rabbitmq
    restart: 
      always
    mem_limit: 
      "1g"
    cpus: 
      "0.5"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}  # user
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}  # pass
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}  # Create vhost, it's like namespace
    ports:
      - "5672:5672"  # amqp port - between microservices
      - "15672:15672"  # web port - ui
    networks:
      - docker-stack
    volumes:
      - ./volumes/rabbitmq_data:/var/lib/rabbitmq  # vol - persistence
      - ./volumes/rabbitmq_logs:/var/log/rabbitmq  # vol - logs

networks:
  docker-stack:
    external: true