version: '3.9'
services:
  mongodb:
    image: 
      mongo:latest
    container_name: 
      own-mongodb
    restart: 
      always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./volumes:/data/db
      - ./init-scripts/A_users.js:/docker-entrypoint-initdb.d/A_users.js:ro
      - ./init-scripts/B_db_default_collections.js:/docker-entrypoint-initdb.d/B_db_default_collections.js:ro
      - ./init-scripts/C_db_com_misciot_collections.js:/docker-entrypoint-initdb.d/C_db_com_misciot_collections.js:ro
      - ./init-scripts/D_db_cars_collections.js:/docker-entrypoint-initdb.d/D_db_cars_collections.js:ro
    networks:
      - claro-mongodb

networks:
  claro-mongodb:
    external: true