services:
  mongodb:
    image: 
      mongo:latest
    container_name: 
      mongodb
    restart: 
      always
    mem_limit: 
      "1g"
    cpus: 
      "0.5"
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./volumes:/data/db
      - ./scripts/1_users.js:/docker-entrypoint-initdb.d/1_users.js:ro
      - ./scripts/2_db_default_collections.js:/docker-entrypoint-initdb.d/2_db_default_collections.js:ro
      - ./scripts/3_db_com_misciot_collections.js:/docker-entrypoint-initdb.d/3_db_com_misciot_collections.js:ro
      - ./scripts/4_db_cars_collections.js:/docker-entrypoint-initdb.d/4_db_cars_collections.js:ro
    networks:
      - docker-stack

networks:
  docker-stack:
    external: true