services:
    mysql:
        image: 
            mysql:8.0
        container_name: 
            mysql
        restart: 
            always
        ports:
            - "3306:3306"
        mem_limit: 
            "1g"
        cpus: 
            "1"
        networks:
            - docker-stack
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./volumes/mysql:/var/lib/mysql
            - ./volumes/init:/docker-entrypoint-initdb.d
            - ./volumes/mycnf/my.cnf:/etc/my.cnf

networks:
    docker-stack:
        external: true
